Adding the other comment route (the route to comment a comment..)
NganeEmmanuel/Socialize pull request #20
Opened 2024-06-02 16:11 UTC by Nde-Dilan

2024-06-02 17:04 UTC, NganeEmmanuel requested changes
Review change request. Also, send me the test case on WhatsApp, screenshot please.

2024-06-02 17:04 UTC, NganeEmmanuel commented on src/main/java/com/socialize/service/entityService/CommentServiceImpl.java
Use the logger in the service class just in the catch blocks remove the ones in the try block

Also use the ```orElseThrow() ``` after calling the repository class then throw the customer error. The code is neater like that. Which means this if block should not exist

```
if(comments.isEmpty()){
                throw new NoChildCommentFoundException(postId,parentCommentId);
            }
```

2024-06-02 19:59 UTC, Nde-Dilan commented on src/main/java/com/socialize/exception/handler/GlobalExceptionHandler.java
Not me, InteliJ reformatted the code to import all of them at once.

2024-06-02 20:00 UTC, Nde-Dilan commented on src/main/java/com/socialize/service/entityService/CommentServiceImpl.java
ok

2024-06-02 20:50 UTC, Nde-Dilan commented on src/main/java/com/socialize/service/entityService/CommentServiceImpl.java
But how should I do it? I'm seeing that I needt to make some metods return an Optional<T> to be able to use that orElseThrow() ,which will cause me to refactor where I am already using them and it's breaking some working ones.

So what should i do?

2024-06-03 11:52 UTC, Nde-Dilan commented on src/main/java/com/socialize/service/entityService/CommentServiceImpl.java
After making the repository method return an Optional<T> and using the  orElseThrow() if the reponse is an empty array am not getting the expected 404.

2024-06-03 18:52 UTC, NganeEmmanuel commented on src/main/java/com/socialize/exception/handler/GlobalExceptionHandler.java
How? Please add the refactored lines of code here so I can see. Cause for now I don't. Essentially I see import statements being removedwhich are essential for using each classes with that class

2024-06-03 18:56 UTC, NganeEmmanuel commented on src/main/java/com/socialize/service/entityService/CommentServiceImpl.java
An empty array means you are not getting nothing from the DB. So your code in the service classes should account for an empty set. The optional is used a nd the orElseThrow is used to to prevent this. So try debugging the code, use line breaks in your code when you run in debug mode to see if all your methods are been accessed and check the variables too. So you want to focus on the controller class where you return the 404 and test that case in debug mode

2024-06-03 19:14 UTC, NganeEmmanuel requested changes

2024-06-03 19:14 UTC, NganeEmmanuel commented on src/main/java/com/socialize/controller/CommentController.java
Also, please remove the nulls in the. Body() an  pass a proper error message

2024-06-03 19:14 UTC, NganeEmmanuel commented on src/main/java/com/socialize/exception/handler/GlobalExceptionHandler.java
Oh, OK I see. Sorry

2024-06-03 19:14 UTC, NganeEmmanuel commented on src/main/java/com/socialize/service/entityService/CommentServiceImpl.java
Not sure anything has changed in this file. Still seeing the if block to throw. Make use of or Else throw.

2024-06-03 19:14 UTC, NganeEmmanuel commented on src/main/java/com/socialize/repository/CommentRepository.java
So both your comment methods should return an optional.

2024-06-09 12:33 UTC, closed without merging